export const ACTION_CODES_EXPIRES = {
	EMAIL_VERIFICATION: 60 * 60 * 24,
	PASSWORD_RESET: 60 * 60 * 24,
	WORKSPACE_INVITE: 60 * 60 * 24,
};

export const ACTION_CODES_TYPES = {
	UNDEFINED: 0,
	EMAIL_VERIFICATION: 1,
	PASSWORD_RESET: 2,
	EMAIL_CHANGE: 3,
	WORKSPACE_INVITE: 4,
};
